source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlarmKit_Example', :exclusive => true do
  pod "AlarmKit", :path => "../"
end

target 'AlarmKit_Tests', :exclusive => true do
  pod "AlarmKit", :path => "../"

  
end
