# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace Example/AlarmKit.xcworkspace -scheme AlarmKit-Example -sdk iphonesimulator9.1 -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
  - pod lib lint
